services:
  database:
    container_name: mongo-server
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=fastFood

    ports:
      - "27017:27017"

  database-adm-tools:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://root:${DB_PASSWORD}@${DB_CONTAINER_NAME}:${DB_PORT}/
    links:
      - database
    depends_on:
      - database


  application:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT= ${DB_PORT}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
    depends_on:
      - database



