services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
    container_name: mongodb

  database-adm-tools:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD:-root}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-root}
    links:
      - database
    depends_on:
      - database
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge