services:
  database:
    container_name: mongo-server
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - "27017:27017"
    #networks:
      #- mongo-compose-network

  database-adm-tools:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-server:27017/
      ME_CONFIG_BASICAUTH: false
    links:
      - database
    depends_on:
      - database
    #networks:
      #- mongo-compose-network

#networks:
  #mongo-compose-network:
    #driver: bridge